### ISSUE TITLE
Make it systemd compatible

### ISSUE THREAD

**Issue by njam** [cargomedia/foreman-debian#24]
Currently uses systemd's sysvinit compatibility layer.
Issues with that:
- Doesn't call `systemctl daemon-reload` after installing script 
 - Workaround: [pulsar-conf-cargomedia deploy.rb](https://github.com/cargomedia/pulsar-conf-cargomedia/pull/320/files#diff-2af499418c5fea8cc9eac1f89935cbc2R73)
- The monit template restarts the daemon (which it shouldn't, because systemd already does that).
 - See [monit_config.erb](https://github.com/cargomedia/foreman-debian/blob/master/templates/monit_config.erb)

**Comment by njam** [comment]
@tomaszdurka @ppp0 @kris-lab thoughts?

**Comment by njam** [comment]
Copying Philipp:
> The problem I see is that the reason to add a suffix `-debian` to foreman was to denote the fact that it is kind of a clone of foreman. Which itself supports systemd! (see http://ddollar.github.io/foreman/#SYSTEMD-EXPORT)

**Comment by ppp0** [comment]
my thoughts are written in https://github.com/cargomedia/puppet-packages/issues/1346#issuecomment-235401826

**Comment by kris-lab** [comment]
@ppp0 agree and see your point. However we need `foreman` support for both (wheezy, jessie) + current custom wheezy workflow (monit). It leads to implement something on top of `foreman` e.g. `foreman-debian`. Please correct me if I am wrong. On the other hand, if we drop wheezy then `foreman-debian` might be too big overhead!

@tomaszdurka wdyt?

**Comment by tomaszdurka** [comment]
Foreman is tool designed to streamline application processes.
Its basic usage is to `start` commands in current (foreman's) process.
But it also has more powerful, helpful commands like `export` to create init system scripts to manipulate and keep alive those processes on system level.

When we've picked up foreman we've been based on wheezy with init.d. First I tried to use native foreman. There was no exporter for init.d, so I tried to implement one. After quick implementation I realized that we needed a bit more than `init.d` scripts provided. Init.d scripts are quite limited - they don't support keepalive and many more functions. Then in order to have systemd-like functionality we needed monit configs. One way was to create another exporter for monit and run them together, but monit configs are connected directly to init.d scripts and not to Procfile commands. That's when `foreman-debian` gem was created.

This project (`foreman-debian`) wasn't named to "rule them all", but simply describes our foreman/debian related needs at that time.

Summarizing I would not prolong foreman-debian's life if not really necessary. Let's try systemd exporter alone?

Note: We might miss some functionalities.
- restart all
- make sure obsolete scripts are removed

**Comment by ppp0** [comment]
Quoting @tomaszdurka 
>Init.d scripts are quite limited - they don't support keepalive

I think in foreman it's accomplished by manipulating `inittab` instead of juggling with scripts. We otoh used monit to keep the processes alive.

Either way: My opinion (vote?) on this is that we shouldn't break our legs to expand foreman-debian with functionality which is available in foreman proper at almost zero cost (except for the changes in pulsar-conf-cargomedia). I.e. we should move to foreman and eventually mothball foreman-debian

**Comment by njam** [comment]
Agree, so let's test if and how we can achieve the result we want with *foreman* (creating, starting, stopping, removing). Let's make sure the unit configuration is as expected (stopping sequence.

@kris-lab wanna migrate this ticket to pulsar-conf-cargomedia then?

**Comment by kris-lab** [comment]
Agree and yes!

**Comment by kris-lab** [comment]
Closing in favor of https://github.com/cargomedia/pulsar-conf-cargomedia/issues/331

please re-open if relevant
